### ISSUE TITLE
Info/Rules Channel Manager Plugin

### ISSUE THREAD

**Issue by rubellyte** [medeor413/Red_Star_Plugins#4]
A plugin to make creating and updating fancy info/rule channels easier.
Potential features:
- Upload a large text file (or maybe JSON?) and have the bot automatically split and post it
- Automatically update the messages in the channel when changes are made
- Image support (I'm not sure how it could be done with attachments; probably best to just let people attach a link to be embedded?)
- Perhaps embed support (this would better lend itself to JSON but could be done in text too)
- Maybe use some sort of diffing to only edit the messages that have been changed?

**Comment by GTG3000** [comment]
I thought about doing that with json like
```json
[
	{
		"message": "2000 chars worth.",
		"embed": {...},
		"attach": ["filename.png", "https://link.com"]
	}
]
```

But that obviously puts more work on the shoulders of whoever's writing it. I *think* it'd be better in the end because auto-splitting can produce some curious results, especially if the end users forget about it and try to have some formatting start in one message and end in another one.

...editing messages could be done by storing the IDs and some sort of a hash per message and comparing them every few global timer ticks?
Probably start by just doing purge/repost. Because that won't break (even if it may take a bit with multiple messages).

**Comment by rubellyte** [comment]
Yeah, I guess it's a balance between user-friendliness and ease of coding. I think your way with the JSON sounds reasonable, though maybe allow users to just put in a string in the list instead of an object if they just want to send normal text.

I'm not sure why you'd want to compare them every few global ticks; it should be enough to only do a check after the schematic is edited. No reason to worry about the fancy edit-if-necessary bits for a v1 though, like you said.

Your point about auto-splitting is good, and reminds me that it would probably be a good idea to deal with the auto-splitting mess in the main code a bit better.

**Comment by GTG3000** [comment]
Yeah, allowing for straight up strings seems logical.

And good point, no reason it needs to be done anywhere other than on reload/file upload. Could also add a nice verification printout for problems per-message like text being too long or files being unavailable.
Not sure how useful local filenames can be, to be honest, since only bot maintainers can access that (and since it would add extra clutter).
